### ISSUE TITLE
subprocess calls vs. importing?

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [liloman/pomodoroTasks2#3]
I was working on a setuptools script for a possible AUR package and noticed you often make use of subprocesses where you could instead have imported the module and called any functions directly. Is there any particular reason why you chose to do things this way? 

I ask because if you want to install this on a system, it breaks the relative paths for these subprocess calls whereas importing these as modules  would work from anywhere. You'll obviously get to review any changes for a pull request, but I figured I'd ask for your reasoning before I start making drastic changes.

**Comment by liloman** [comment]
Hi :)

> I was working on a setuptools script for a possible AUR package and noticed you often make use of subprocesses where you could instead have imported the module and called any functions directly. Is there any particular reason why you chose to do things this way?

Awesome about the AUR package. 

About subprocess issue,  do you mind be more specific?  

I'm a python noob but I think I used subprocess because the dbus has to run in its own process/thread/loop and it's also the case of GTK. ;)

>I ask because if you want to install this on a system, it breaks the relative paths for these subprocess calls whereas importing these as modules would work from anywhere. You'll obviously get to review any changes for a pull request, but I figured I'd ask for your reasoning before I start making drastic changes.

Do you mean the timew related lines?

```bash
 subprocess.Popen(['timew', 'stop'])
```

By the way, do you have any issues with shutting down, suspending/resuming and so on.  I find quite cumbersome that sometimes it doesn't stop tracking and later when I resume/power on the computer I realise that It didn't stop tracking, that really pisses me off. I have put some work into the systemd services in that direction but I think there's something out of control there and quite cumbersome.  Do you have any issues with that?

**Comment by MadeOfMagicAndWires** [comment]
with the subprocess calls I was mostly talking about things like [these](../master/pomodoro-daemon.py#L336)
```python
   subprocess.Popen(['./pomodoro-systray.py', sys.argv[1]])
```
I haven't worked with dbus myself too much but soon after posting this I probably realised it was some producer-consumer related reason. 

In the end it doesn't matter *too* much, I can make it work with the subprocesses too, but it's still feels a bit off as now you've got two separate processes running for the daemon, one of which requires a graphical interface. 
Normally you'd run a headless daemon and tie the GUI to the client but I think that's more an issue for another time. For now I'll see how to implement things with the current setup and see where we can take it from there.

**Comment by MadeOfMagicAndWires** [comment]
P.S.

As for your gripes with timew, I had the same issue and eventually created [this script](https://gist.github.com/MadeOfMagicAndWires/e48284f7fe7776d4eb30ffc113609023) to stop all timers on shutdown. 
It's a lot simpler than a special unit file and as far as I know you can do the same thing when sleeping the system by installing it to `/usr/lib/systemd/system-sleep/` rather than `/usr/lib/system-shutdown/`. You'll still have to manually start the timer on startup though, but I think it's better that way anyway.

**Comment by liloman** [comment]
Hi, 

That a long standing issue, as it is the second version I learned some things. :)

I'll say that launching the systray with the daemon it's for UX purposes (in my opinion), alike to shuting down the daemon with the systray, they're built separately but coupled. ;)
