### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by real-or-random** [liloman/pomodoroTasks2#5]
Great project!

I guess there was a reason to use Python 2 but given this is a relatively new project, wouldn't it be better to switch Python 3 instead?
https://wiki.python.org/moin/Python2orPython3

(Porting now may be easier than later.)

**Comment by liloman** [comment]
Thanks!

I don't have any issue about porting it to Python 3. :)
So any contribution will be accepted. 

But take it easy cause I don't have so much spare time lately. :)

Cheers

**Comment by liloman** [comment]
Done: 
https://github.com/liloman/pomodoroTasks2/commit/1d6d3ae03edd0c96cffdcd2aa8d211d2e7f74598 :)

**Comment by real-or-random** [comment]
Great. :)
