### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by dimas-cyriaco** [liloman/pomodoroTasks2#6]
I'm trying to install on Ubuntu 17.04 without success.

The first problem is that the readme seems to be outdated. It tell me to run `./pomodoro-daemon.py` but this file does not exists. There is a `pomodorotasks/daemon.py`. Is this the same thing?

I've tried to run that and got an error:

```
Traceback (most recent call last):
  File "./pomodorotasks/daemon.py", line 6, in <module>
    from builtins import str
ImportError: No module named builtins
```

I've noticed a `setup.py` file on the root of the project. Do I have to run that?

I've tried, bug the shebang is pointing to the wrong path. It's pointing to `/bin/env` but my Ubuntu install has the `env` utility on `/usr/bin/env`. So I edited it and then I tried:

```
./setup.py build
./setup.py install
```

This seems to work. I got:

```
Installing pomodoro-tasks-client script to /usr/local/bin
Installing pomodoro-tasks-daemon script to /usr/local/bin
```

But trying to run the daemon throws me this:

```
Traceback (most recent call last):
  File "/usr/local/bin/pomodoro-tasks-daemon", line 6, in <module>
    from pomodorotasks.daemon import main
  File "/usr/local/lib/python2.7/dist-packages/pomodorotasks/daemon.py", line 6, in <module>
    from builtins import str
ImportError: No module named builtins
```

Maybe I have the wrong Python version? I'm using `Python 2.7.13`.

**Comment by liloman** [comment]
Hi @dimascyriaco ,

You're right. 
I fixed it, try pulling all branches and checking out the stable branch first. ;)

```bash
git checkout stable
```


Cheers
